// ABINITIA — Mock Data for MVP
import type { Family, Person, TreeNode, TreeEdge, Story, TimelineEvent, JoinRequest, BookChapter, FamilyMember } from '@/types'

export const MOCK_FAMILIES: Family[] = [
  {
    id: 'fam-001',
    name: 'Ferraro',
    surname: 'Ferraro',
    description: 'Família italiana com raízes em Nápoles, chegou ao Brasil em 1888.',
    origin: 'Nápoles, Itália',
    symbol: '🌿',
    motto: 'Ferro e esperança',
    isPublic: true,
    adminId: 'user-001',
    createdAt: new Date('2026-01-15'),
    stats: {
      people: 284,
      generations: 7,
      stories: 126,
      documents: 342,
      photos: 817,
      audios: 58,
      events: 193,
      bookProgress: 72,
      pendingInvestigations: 14,
      newCollaborators: 3,
    },
  },
  {
    id: 'fam-002',
    name: 'Silva',
    surname: 'Silva',
    description: 'Família mineira com séculos de história no Brasil.',
    origin: 'Minas Gerais, Brasil',
    symbol: '🌳',
    isPublic: true,
    adminId: 'user-002',
    createdAt: new Date('2026-02-10'),
    stats: {
      people: 156,
      generations: 5,
      stories: 88,
      documents: 210,
      photos: 445,
      audios: 32,
      events: 134,
      bookProgress: 45,
      pendingInvestigations: 8,
      newCollaborators: 1,
    },
  },
  {
    id: 'fam-003',
    name: 'Costa',
    surname: 'Costa',
    description: 'Família com raízes em Portugal e no Rio de Janeiro.',
    origin: 'Porto, Portugal · Rio de Janeiro, Brasil',
    symbol: '🔒',
    isPublic: false,
    adminId: 'user-003',
    createdAt: new Date('2026-03-05'),
    stats: {
      people: 98,
      generations: 4,
      stories: 45,
      documents: 134,
      photos: 223,
      audios: 18,
      events: 89,
      bookProgress: 28,
      pendingInvestigations: 22,
      newCollaborators: 0,
    },
  },
]

export const MOCK_PEOPLE: Person[] = [
  {
    id: 'p-001',
    familyId: 'fam-001',
    firstName: 'Giuseppe',
    lastName: 'Ferraro',
    birthDate: '1865',
    birthPlace: 'Nápoles, Itália',
    deathDate: '1942',
    deathPlace: 'São Paulo, Brasil',
    gender: 'M',
    occupation: 'Ferreiro',
    nationality: 'Italiana',
    notes: 'Fundador da família no Brasil. Chegou ao Porto de Santos em 1888.',
    evidenceStatus: 'CONFIRMED',
    createdById: 'user-001',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'p-002',
    familyId: 'fam-001',
    firstName: 'Rosa',
    lastName: 'Ferraro',
    aliases: ['Rosa Carbone'],
    birthDate: '1870',
    birthPlace: 'Salerno, Itália',
    deathDate: '1955',
    deathPlace: 'São Paulo, Brasil',
    gender: 'F',
    occupation: 'Costureira',
    nationality: 'Italiana',
    evidenceStatus: 'CONFIRMED',
    createdById: 'user-001',
    createdAt: new Date('2026-01-16'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'p-003',
    familyId: 'fam-001',
    firstName: 'Antonio',
    lastName: 'Ferraro',
    birthDate: '1895',
    birthPlace: 'São Paulo, Brasil',
    deathDate: '1968',
    gender: 'M',
    occupation: 'Comerciante',
    nationality: 'Brasileira',
    evidenceStatus: 'CONFIRMED',
    createdById: 'user-001',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'p-004',
    familyId: 'fam-001',
    firstName: 'Maria',
    lastName: 'Ferraro',
    birthDate: '1898',
    birthPlace: 'São Paulo, Brasil',
    deathDate: '1985',
    gender: 'F',
    evidenceStatus: 'CONFIRMED',
    createdById: 'user-001',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'p-005',
    familyId: 'fam-001',
    firstName: 'Carlos',
    lastName: 'Ferraro',
    birthDate: '1928',
    deathDate: '2020',
    gender: 'M',
    occupation: 'Engenheiro',
    evidenceStatus: 'CONFIRMED',
    createdById: 'user-001',
    createdAt: new Date('2026-01-22'),
    updatedAt: new Date('2026-01-22'),
  },
  {
    id: 'p-006',
    familyId: 'fam-001',
    firstName: 'Carolina',
    lastName: 'Ferraro',
    birthDate: '1985',
    gender: 'F',
    occupation: 'Advogada',
    evidenceStatus: 'CONFIRMED',
    userId: 'user-001',
    createdById: 'user-001',
    createdAt: new Date('2026-01-22'),
    updatedAt: new Date('2026-01-22'),
  },
]

export const MOCK_TREE_NODES: TreeNode[] = [
  { person: MOCK_PEOPLE[0], x: 400, y: 80,  generation: 1, children: ['p-003', 'p-004'], parents: [], partners: ['p-002'] },
  { person: MOCK_PEOPLE[1], x: 600, y: 80,  generation: 1, children: ['p-003', 'p-004'], parents: [], partners: ['p-001'] },
  { person: MOCK_PEOPLE[2], x: 280, y: 240, generation: 2, children: ['p-005'], parents: ['p-001', 'p-002'], partners: [] },
  { person: MOCK_PEOPLE[3], x: 550, y: 240, generation: 2, children: [], parents: ['p-001', 'p-002'], partners: [] },
  { person: MOCK_PEOPLE[4], x: 280, y: 400, generation: 3, children: ['p-006'], parents: ['p-003'], partners: [] },
  { person: MOCK_PEOPLE[5], x: 280, y: 560, generation: 4, children: [], parents: ['p-005'], partners: [] },
]

export const MOCK_TREE_EDGES: TreeEdge[] = [
  { from: 'p-001', to: 'p-002', type: 'SPOUSE' },
  { from: 'p-001', to: 'p-003', type: 'PARENT_CHILD' },
  { from: 'p-001', to: 'p-004', type: 'PARENT_CHILD' },
  { from: 'p-002', to: 'p-003', type: 'PARENT_CHILD' },
  { from: 'p-002', to: 'p-004', type: 'PARENT_CHILD' },
  { from: 'p-003', to: 'p-005', type: 'PARENT_CHILD' },
  { from: 'p-005', to: 'p-006', type: 'PARENT_CHILD' },
]

export const MOCK_STORIES: Story[] = [
  {
    id: 's-001',
    familyId: 'fam-001',
    title: 'A chegada ao Brasil',
    content: 'Giuseppe chegou ao Porto de Santos em 1888, trazendo na bagagem apenas as ferramentas do ofício e a esperança de uma vida melhor. Conta a história que ele chorou ao avistar o litoral brasileiro pela primeira vez.',
    originalContent: 'Meu bisavô chegou ao Brasil em 1888... ele chorou ao ver a costa...',
    authorId: 'user-001',
    associatedPersonIds: ['p-001'],
    visibility: 'FAMILY',
    evidenceStatus: 'REPORTED',
    createdAt: new Date('2026-02-01'),
  },
  {
    id: 's-002',
    familyId: 'fam-001',
    title: 'A ferraria da Rua do Comércio',
    content: 'Por volta de 1905, Giuseppe abriu sua ferraria na Rua do Comércio, no centro de São Paulo. O negócio prosperou e permitiu que os filhos estudassem.',
    authorId: 'user-001',
    associatedPersonIds: ['p-001', 'p-002'],
    visibility: 'BOOK',
    evidenceStatus: 'CONFIRMED',
    createdAt: new Date('2026-02-15'),
  },
]

export const MOCK_TIMELINE: TimelineEvent[] = [
  { id: 'e-001', familyId: 'fam-001', title: 'Nascimento de Giuseppe', type: 'BIRTH', date: '1865', personIds: ['p-001'], location: 'Nápoles, Itália', evidenceStatus: 'CONFIRMED' },
  { id: 'e-002', familyId: 'fam-001', title: 'Casamento de Giuseppe e Rosa', type: 'MARRIAGE', date: '1887', personIds: ['p-001', 'p-002'], location: 'Nápoles, Itália', evidenceStatus: 'CONFIRMED' },
  { id: 'e-003', familyId: 'fam-001', title: 'Migração para o Brasil', type: 'MIGRATION', date: '1888', personIds: ['p-001', 'p-002'], location: 'Santos, Brasil', evidenceStatus: 'CONFIRMED', description: 'Chegada ao Porto de Santos' },
  { id: 'e-004', familyId: 'fam-001', title: 'Abertura da Ferraria Ferraro', type: 'PROFESSION', date: '1905', personIds: ['p-001'], location: 'São Paulo, SP', evidenceStatus: 'REPORTED' },
  { id: 'e-005', familyId: 'fam-001', title: 'Nascimento de Antonio', type: 'BIRTH', date: '1895', personIds: ['p-003'], location: 'São Paulo, Brasil', evidenceStatus: 'CONFIRMED' },
  { id: 'e-006', familyId: 'fam-001', title: 'Falecimento de Giuseppe', type: 'DEATH', date: '1942', personIds: ['p-001'], evidenceStatus: 'CONFIRMED' },
  { id: 'e-007', familyId: 'fam-001', title: 'Nascimento de Carolina', type: 'BIRTH', date: '1985', personIds: ['p-006'], location: 'São Paulo, Brasil', evidenceStatus: 'CONFIRMED' },
]

export const MOCK_JOIN_REQUESTS: JoinRequest[] = [
  {
    id: 'jr-001',
    familyId: 'fam-001',
    userId: 'user-010',
    userName: 'Roberto Ferraro',
    userEmail: 'roberto.ferraro@email.com',
    targetPersonId: 'p-005',
    message: 'Sou filho de Carlos Ferraro. Meu pai me contou sobre a família.',
    status: 'PENDING',
    createdAt: new Date('2026-09-10'),
  },
  {
    id: 'jr-002',
    familyId: 'fam-001',
    userId: 'user-011',
    userName: 'Lucia Ferraro Santos',
    userEmail: 'lucia.fsantos@email.com',
    targetPersonId: 'p-004',
    message: 'Sou neta de Maria Ferraro pelo lado de minha mãe.',
    status: 'PENDING',
    createdAt: new Date('2026-09-11'),
  },
]

export const MOCK_BOOK_CHAPTERS: BookChapter[] = [
  { id: 'ch-001', familyId: 'fam-001', title: 'As origens italianas', content: '...', order: 1, generationFrom: 1, generationTo: 1, status: 'PUBLISHED', storyIds: ['s-001'] },
  { id: 'ch-002', familyId: 'fam-001', title: 'A chegada ao Brasil', content: '...', order: 2, generationFrom: 1, generationTo: 2, status: 'PUBLISHED', storyIds: ['s-001', 's-002'] },
  { id: 'ch-003', familyId: 'fam-001', title: 'A família no século XX', content: '...', order: 3, generationFrom: 2, generationTo: 3, status: 'DRAFT', storyIds: [] },
  { id: 'ch-004', familyId: 'fam-001', title: 'Os descendentes', content: '...', order: 4, generationFrom: 3, generationTo: 4, status: 'DRAFT', storyIds: [] },
  { id: 'ch-005', familyId: 'fam-001', title: 'A geração atual', content: '...', order: 5, status: 'DRAFT', storyIds: [] },
]

export const MOCK_MEMBERS: FamilyMember[] = [
  { userId: 'user-001', familyId: 'fam-001', personId: 'p-006', role: 'ADMIN', joinedAt: new Date('2026-01-15') },
  { userId: 'user-002', familyId: 'fam-001', personId: 'p-005', role: 'CONTRIBUTOR', joinedAt: new Date('2026-02-01') },
  { userId: 'user-003', familyId: 'fam-001', role: 'READER', joinedAt: new Date('2026-03-10') },
]

export const CURRENT_USER = {
  id: 'user-001',
  name: 'Carolina Ferraro',
  email: 'carolina@ferraro.com',
  avatar: undefined,
  createdAt: new Date('2026-01-15'),
}
